server {
    listen 80;
    server_name localhost;
    root /var/www/html/public; # ThinkPHP 的入口目录
    index index.php index.html index.htm;

    # ThinkPHP 必须的伪静态配置
    location / {
        if (!-e $request_filename) {
            rewrite  ^(.*)$  /index.php?s=/$1  last;
            break;
        }
    }

    # 处理 PHP 请求
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000; # 转发给本机的 PHP-FPM
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # 允许上传大文件
    client_max_body_size 20m;
}
