apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinkphp-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thinkphp
  template:
    metadata:
      labels:
        app: thinkphp
    spec:
      # --- 关键配置：指定节点名称 ---
      nodeName: hk-edge-1 
      
      containers:
      - name: php-nginx
        image: ghcr.io/gop206/thinkphp:latest  # 确保你已经解决了 push 权限问题
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "40"   # 允许利用高性能节点的算力
            memory: "16Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: thinkphp-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: thinkphp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # 外部访问端口
