apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinkphp-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thinkphp
  template:
    metadata:
      labels:
        app: thinkphp
    spec:
      # --- 指定节点名称 ---
      nodeName: hk-edge-1 
      
      containers:
      - name: php-nginx
        image: ghcr.io/gop206/thinkphp:latest  
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "40"  
            memory: "16Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: thinkphp-service
  namespace: prod
spec:
  type: ClusterIP 
  selector:
    app: thinkphp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
